### ISSUE TITLE
[Question] How is teardown done for mutual foreign keys?

### ISSUE THREAD

**Issue by jsmaniac** [morphismtech/squeal#128]
Hi!

I saw @Raveline's presentation at the Paris Haskell meetup this week (great presentation!).

From what I understood, the type system prevents deleting a table which is referenced by foreign keys, when defining a `teardown` migration (see [Defining our first migration](https://github.com/morphismtech/squeal/blob/dev/squeal-presentation-raveline.md#defining-our-first-migration)). That seems fair enough :) .

If there are two mutually-referencing tables, how can they both be (atomically) deleted ?

Thanks,
Georges Dupéron

**Comment by echatav** [comment]
I'm not sure Squeal does anything to prevent you from dropping tables with mutual foreign keys. Have you tried to do that and gotten either a compile time error or a runtime error? If you get a runtime error because Postgres has a problem with it then you should first use `alterTable _ $ dropConstraint _` twice to drop the references.

**Comment by jsmaniac** [comment]
I see. In the the live version of the presentation, there were two tables to be dropped by `teardown`, and I misunderstood that these had to be listed in the opposite order of their creation order, in order not to temporarily break Foreign Key constraints.

I haven't tried this on an example, and was simply curious after the presentation :) . Thanks and sorry for the noise!
