### ISSUE TITLE
Is there a way to insert an unknown amount of things using Values?

### ISSUE THREAD

**Issue by Zer0-** [morphismtech/squeal#155]
In the example in the Readme, suppose we changed the User's emailField definition from `userEmail :: Maybe Text` to `userEmail :: [Text]` and I wanted to insert a user with a list of emails. If I were writing the query by hand, I would just specify more than one thing in my VALUES expression.
But it looks like to use Values (from Manipulation) I need to know how many emails I am going to insert beforehand, because I have to write (param @x) by hand for each.

I can always just insert emails by using `traversePrepared_` with a manipulation that inserts a single email after I have created the user, but then doesn't that make a separate database call for each email or would that be equivalent to using multi-row Values in terms of performance?

IRL I have something very similar to the user - email relationship, it's a document and a list of files. This is my first time using squeal and I am just trying to insert things.

**Comment by echatav** [comment]
You want to look at the `PGvararray` type. Instead of `"email" ::: 'NoDef :=> 'Null 'PGtext`, your user table will have `"email" ::: 'NoDef :=> 'NotNull ('PGvararray ('NotNull 'PGtext))`. Then on the Haskell side, instead of `userEmail :: Maybe Text` your user datatype will have `userEmail :: VarArray [Text]`. `VarArray` is just a newtype which ensures that what it contains will be stored as an array in the database.

**Comment by echatav** [comment]
Or, if you want to leave the tables the way they are, then you could use `traversePrepared_` like you said. From Postgres's docs:

> PREPARE creates a prepared statement. A prepared statement is a server-side object that can be used to optimize performance. When the PREPARE statement is executed, the specified statement is parsed, analyzed, and rewritten. When an EXECUTE command is subsequently issued, the prepared statement is planned and executed. This division of labor avoids repetitive parse analysis work, while allowing the execution plan to depend on the specific parameter values supplied.

Another alternative if you're still worried about calling EXECUTE multiple times, you can break `insertUser`  into two inserts one for the user table and one for the email table. For the email table you can use a `Values` clause in the way you said. It takes essentially a non-empty list, which you'll have to use inline in the query, rather than as a single out-of-line parameter.

**Comment by Zer0-** [comment]
Thank you echatav! I think a separate call for inserting emails is what I want to do. Could you please give me an example of how to use `Values` as you said? In the code all the examples are for using `Values_`.

> It takes essentially a non-empty list, which you'll have to use inline in the query, rather than as a single out-of-line parameter

I'm not 100% sure what you meant by this, does that mean there is no way to dynamically create the list (the last argument to `Values`) if you don't know how many emails you will have?

**Comment by echatav** [comment]
```Haskell
>>> type Columns = '["col1" ::: 'NoDef :=> 'Null 'PGint4, "col2" ::: 'Def :=> 'NotNull 'PGint4]
>>> type Schema = '["tab" ::: 'Table ('[] :=> Columns)]
>>> :{
let
  manipulation :: Manipulation_ (Public Schema) () ()
  manipulation =
    insertInto_ #tab $ Values
      [ Set 1 `as` #col1 :* Set 1 `as` #col2
      , Set 2 `as` #col1 :* Default `as` #col2 ]
      ( Set 3 `as` #col1 :* Default `as` #col2 )
in printSQL manipulation
:}
INSERT INTO "tab" ("col1", "col2") VALUES (1, 1), (2, DEFAULT), (3, DEFAULT)
```

**Comment by Zer0-** [comment]
You are the best!
