### ISSUE TITLE
How to create a ForeignKey referencing its own table ?

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#27]
Picture a very simple table of words, with a column potentially joining on the same table:

```
type Schema =
  '[ "words" :::
     '[ "pk_words" ::: 'PrimaryKey '["word_id"]
      , "fk_words" ::: 'ForeignKey '["lemma"] "words" '["word_id"]
      ] :=>
     '[ "word_id" :::   'Def :=> 'NotNull 'PGint4
      , "form"    ::: 'NoDef :=> 'NotNull 'PGtext
      , "lemma"   ::: 'NoDef :=>    'Null 'PGint4 ]
   ]
```

When I try to write the Definition for this table, the compiler is not pleased. Here is my attempt:

```
setup :: Definition '[] Schema
setup =
  createTable #words
  ( serial `As` #word_id :*
    (text &notNull) `As` #form :*
    int `As` #lemma :* Nil
  )
  ( primaryKey (Column #word_id :* Nil) `As` #pk_words :*
    foreignKey (Column #lemma :* Nil) #words (Column #word_id :* Nil )
      OnDeleteNoAction OnUpdateNoAction `As` #fk_words :* Nil)
```

The main error I get is:

```
No instance for (Has "words" '[] reftable0)
        arising from a use of ‘foreignKey’
```

If I read this properly, the typchecker stores the defined table, and it is not found (probably because the table has not yet been defined). So, am I missing something here ? Is this a known issue ? Is there a workaround ?

**Comment by echatav** [comment]
I hadn't considered self referential foreign keys. I'll have to change something either in `foreignKey`, `createTable` or both. What's happening is that `createTable` is checking the table constraints against the initial schema, in this case `'[]` and not finding the `words` table. For a workaround, you can always use raw SQL. Hopefully this should work:

```haskell
setup :: Definition '[] Schema
setup =
  createTable #words
  ( serial `As` #word_id :*
    (text &notNull) `As` #form :*
    int `As` #lemma :* Nil
  )
  ( primaryKey (Column #word_id :* Nil) `As` #pk_words :* fk `As` #fk_words :* Nil )
  where
    fk = UnsafeTableConstraintExpression "FOREIGN KEY (lemma) REFERENCES words (word_id) ON DELETE NO ACTION ON UPDATE NO ACTION"
```

**Comment by adfretlink** [comment]
I can confirm your workaround compiles, thanks a bunch ! I tried to find one by using `addConstraint` after the createTable but failed (still learning my way around Squeal though so it could still be a viable, type safe solution). I imagine finding a more stable solution is not easy (maybe a specialized function mimicking `foreignKey`, but only used for self referentials fk ?).

In any case, thank you very much for your swift and helpful answer !

**Comment by echatav** [comment]
> I tried to find one by using addConstraint after the createTable

That's a much better workaround since as you point out it's type-safe.

```haskell
:{
type Schema =
  '[ "words" :::
     '[ "pk_words" ::: 'PrimaryKey '["word_id"]
      , "fk_words" ::: 'ForeignKey '["lemma"] "words" '["word_id"]
      ] :=>
     '[ "word_id" :::   'Def :=> 'NotNull 'PGint4
      , "form"    ::: 'NoDef :=> 'NotNull 'PGtext
      , "lemma"   ::: 'NoDef :=> 'NotNull 'PGint4 ]
   ]

setup :: Definition '[] Schema
setup =
  createTable #words
  ( serial `As` #word_id :*
    (text & notNull) `As` #form :*
    (int & notNull) `As` #lemma :* Nil
  )
  ( primaryKey (Column #word_id :* Nil) `As` #pk_words :* Nil)
  >>>
  alterTable #words (addConstraint #fk_words
    (foreignKey (Column #lemma :* Nil) #words (Column #word_id :* Nil )
      OnDeleteNoAction OnUpdateNoAction))
:}
```

I had to change the `lemma` column to be `notNull` because foreign keys cannot be `Null` in Squeal. Reading over the [docs](https://www.postgresql.org/docs/10/static/ddl-constraints.html#DDL-CONSTRAINTS-FK) again it appears that that was too restrictive so maybe another bug?

> I imagine finding a more stable solution is not easy

It's going to require some thought because for now the kind of `TableConstraintExpression` does not contain the information of the table name you're creating.

```haskell
>>> :kind TableConstraintExpression
TableConstraintExpression :: TablesType -> ColumnsType -> TableConstraint -> *
```

The `TablesType` refers to the schema before creating a given table (at least for `createTable`). The `ColumnsType` refers to the columns of the table you're creating and the `TableConstraint` in the type of table constraint you're creating. The table's name is nowhere in there so I'll have to add it and then when checking that the references are valid, join the new table with its columns into the schema and check against the larger schema. I also need to think carefully about the difference in behavior between `createTable` and `alterTable . addConstraint` to make sure it's all right. And given that second bug I'll have to generalize the check to allow for `Null` foreign keys.

**Comment by adfretlink** [comment]
First of all, thanks a lot for the second, type-safe workaround and apologies for taking so long to answer - I missed the notification.

> I had to change the lemma column to be notNull because foreign keys cannot be Null in Squeal. Reading over the docs again it appears that that was too restrictive so maybe another bug?

Well I wouldn't qualify this as a bug, but I think we'll agree it's definitely not SQL standard; any FK can be nullable.

Thank you for the resolving commit ! I'll need to see if this fixes my issue (will try to update you on this as soon as I can).

Maybe it would be a good idea to add some tests schema with undocumented and difficult cases (like null FK and self-FK), both to check for regression and give pointers to newcomers ?

**Comment by echatav** [comment]
I added a doctest which included a self-referencing `NULL` foreign key column [here](https://github.com/morphismtech/squeal/blob/foreignKey%2BandThen%2Bviews%2Btypes/squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs#L353). I made a whole lot of changes including fixing those bugs in this branch so it will be a new version, 0.3. I'm trying to add views, and composite and enum types. I'm a bit stuck now on enums because of [this issue](https://ghc.haskell.org/trac/ghc/ticket/11671?cversion=0&cnum_hist=11).

**Comment by adfretlink** [comment]
Oh, I had missed the new Doctest ! I forgot that your documentation was full of useful examples, I love this, by the way.

Supporting enums would indeed be great. I suppose you need the capitalized labels to support the various constructors for enumerated types ? And the idea would be to map to a psql type creation on schema setup ? That would be ideal indeed (and very close to common production environments). I hope future GHC version will fix this.

**Comment by echatav** [comment]
> I suppose you need the capitalized labels to support the various constructors for enumerated types?

In Squeal, I want Haskell types that are "isomorphic" to PG types to get (near) automatic encoding and decoding instances. But what Haskell types are isomorphic to PG enum types _exactly_? The simplest answer is a Haskell sum type with nullary constructors whose constructors are _exactly_ the same as the PG enum labels. Haskell constructors of course are capitalized and we can grab them at the type level using the magic of [type level](https://ryanglscott.github.io/2016/05/12/whats-new-with-ghc-generics-in-80/) [generic metadata](https://hackage.haskell.org/package/generics-sop-0.3.2.0/docs/Generics-SOP-Type-Metadata.html).

> And the idea would be to map to a psql type creation on schema setup ?

You would define _both_ your Haskell enum and your PG enum.

```Haskell
data Schwarma = Beef | Lamb | Chicken | Camel deriving (Read, Show)
instance SOP.HasDatatypeInfo Schwarma

type PGSchwarma = 'PGenum '["Beef", "Lamb", "Chicken", "Camel"]

createSchwarma :: Definition schema (Create "Schwarma" ('TypeDef PGSchwarma) schema)
createSchwarma = createTypeEnum #schwarma $
  fromLabel @"Beef" :* -- or just `#Beef` when feature #11671 is added
  fromLabel @"Lamb" :*
  fromLabel @"Chicken" :*
  fromLabel @"Camel" :* Nil
```

This might seem like too much writing for something so seemingly simple :-( There really are 2 different types though and at a low level the requirement to define things in both Haskell and SQL. I hope that being low level creates the building blocks for higher level abstraction.

**Comment by echatav** [comment]
It may not be correct to use overloaded labels for PG enum labels. On the PG side, aliases are a very different thing from enum labels. Aliases are either double quoted `"alias"` or simply unmarked `alias` whereas enum labels are PG text values hence single quoted `'label'`. So more correct would be to duplicate the `IsLabel` class to an `IsPGlabel` class and take the opportunity to shorten `fromLabel` to....maybe `label`?

+1 Would avoid overlapping instances from expressions that can be a column alias or can be enum label literal value.
+1 Would obviate worrying about issue #11671
-1 Would be confusing since label now means half a dozen different things!
-1 Not as nice as overloaded labels sugar in terms of sheer shortness, gotta use type application

P.S. Sorry to document thoughts on an unrelated issue thread!

**Comment by adfretlink** [comment]
When I consider the example you gave and particularly the `createSchwarma`, this does indeed seem like a lot of boilerplate for a long Enum.

All right, I might be missing something or thinking wrong - this kind of type level programming is above my level, I only understand how to use it from a library user point of view - but couldn't you make things simpler by leveraging the `Enum` typeclass ? Or there is no way to use the constructor-iteration abilities from `Enum` at this type level ? (I suppose you'd anyway still need to provide a way, for the user, to overload the constructor names in case these conflicts with PG keywords).

In any case, even with the boilerplate, it seems like a good solution. What I particularly like with Squeal is the fact that it is completely decoupling from your model; you can still write your model datatypes as "plain old haskell datatypes". I think this is one the biggest appeal of your library, and I'd be willing to pay writing a lot of boilerplate (or - God help me - learn template haskell !) for this.

**Comment by echatav** [comment]
> but couldn't you make things simpler by leveraging the Enum typeclass ? Or there is no way to use the constructor-iteration abilities from Enum at this type level ?

I'm not sure I understand but I'd think Haskell's `Enum` typeclass would be mostly irrelevant. It ought to give you an isomorphism between a Haskell type and the set `{0,1,...,n}`. I think that's supposed to be like C enums which are [named numbers](https://www.geeksforgeeks.org/enumeration-enum-c/). PG enums as far as I know don't have associated numbers. They are more text like; you express them as literal text like `'Beef'`.

> you can still write your model datatypes as "plain old haskell datatypes".

Can you elaborate on what you mean?

> learn template haskell

I have to learn it too.

**Comment by adfretlink** [comment]
- Concerning the haskell `Enum`, I meant that rather to have to type:

```
createTypeEnum #schwarma $
  fromLabel @"Beef" :* -- or just `#Beef` when feature #11671 is added
  fromLabel @"Lamb" :*
  fromLabel @"Chicken" :*
  fromLabel @"Camel" :* Nil
```

if there was a way, from a haskell datatype having `Enum` to define a label from its constructor, it would be easy to iterate over constructors using Enum (even easier with `Bounded`: `[minBound..maxbound]`), and thus avoid to have to type it all. But once again, due to my lack of knowledge of the behaviour of this kind of type-level programming, what I suggest makes have no sense or be completely impossible.

- As for "plain old haskell datatypes", I mean that in a typical application, you'd have some types laying around (things likes "Employee" and "Department"). And I want to be able to keep these simple and pure. Some other frameworks rarely let you do this: `Persistent` condemn you to use TemplateHaskell, and `Beam` force you to use their `Columnar` functor everywhere. `Squeal` doesn't force me to do this; I can keep my model uncoupled with the serialization solution. That's a really, really great thing about your library. (Well, that and type safe sql queries of course).

- Good luck learning TH :smiley:

**Comment by echatav** [comment]
Hmmm, that does lead to a good idea. We can constrain a Haskell type such that we know it's a sum type with nullary constructors; grab its constructors and form a create statement from that:

```Haskell
createTypeEnumFromHaskell
  :: (IsEnum x, SameLabels (DatatypeInfoOf x) labels)
  => Alias enum
  -> proxy x
  -> Definition schema (Create enum ('TypeDef ('PGenum labels)) schema)
```

Then you would only have to write

```Haskell
createSchwarma = createTypeEnumFromHaskell #schwarma (Proxy @Schwarma)
```

> I can keep my model uncoupled with the serialization solution

Great! This was my hope. I had been annoyed by the same kind of thing in Opaleye. In theory it seems like a good idea to use the same types for Haskell and PG but in practice you end up having to caulk up the cracks in the differences. Separation of concerns is a thing for a reason I guess.

**Comment by adfretlink** [comment]
Yes, that `createTypeEnumFromHaskell` is exactly what I had in mind but couldn't express properly ! That should cover a lot of common use-case.

> This was my hope

I think `Squeal` is the most promising library in this matter and I'm very happy that you're working on it ! I will try to bring you back more feedback (and who knows, maybe contribution) as I keep using it.

**Comment by echatav** [comment]
In addition to being able to encode and decode basic Haskell types like Int16 and Text, Squeal permits you to encode and decode Haskell types which are equivalent to Postgres enumerated and composite types.

Enumerated (enum) types are data types that comprise a static, ordered set of values. They are equivalent to Haskell algebraic data types whose constructors are nullary. An example of an enum type might be the days of the week, or a set of status values for a piece of data.
```Haskell
>>> data Schwarma = Beef | Lamb | Chicken deriving (Show, GHC.Generic)
>>> instance Generic Schwarma
>>> instance HasDatatypeInfo Schwarma
```
A composite type represents the structure of a row or record; it is essentially just a list of field names and their data types. They are almost equivalent to Haskell record types. However, because of the potential presence of NULL all the record fields must be Maybes of basic types.
```Haskell
>>> data Person = Person {name :: Maybe Text, age :: Maybe Int32} deriving (Show, GHC.Generic)
>>> instance Generic Person
>>> instance HasDatatypeInfo Person
```
We can create the equivalent Postgres types directly from their Haskell types.
```Haskell
>>> :{
type Schema =
  '[ "schwarma" ::: 'Typedef (EnumWith Schwarma)
   , "person" ::: 'Typedef (CompositeWith Person)
   ]
:}
>>> :{
let
  setup :: Definition '[] Schema
  setup =
    createTypeEnumWith @Schwarma #schwarma >>>
    createTypeCompositeWith @Person #person
:}
```
Then we can perform roundtrip value queries;
```Haskell
>>> :{
let
  qry1 :: Query Schema
    '[ 'NotNull (EnumWith Schwarma)]
    '["fromOnly" ::: 'NotNull (EnumWith Schwarma)]
  qry1 = values_ (parameter @1 #schwarma `As` #fromOnly :* Nil)
:}
>>> :{
let
  qry2 :: Query Schema
    '[ 'NotNull (CompositeWith Person)]
    '["fromOnly" ::: 'NotNull (CompositeWith Person)]
  qry2 = values_ (parameter @1 #person `As` #fromOnly :* Nil)
:}
```
And finally drop the types.
```Haskell
>>> :{
let
  teardown :: Definition Schema '[]
  teardown = dropType #schwarma >>> dropType #person
:}
```
Now let's run it.
```Haskell
>>> :{
let
  session = do
    result1 <- runQueryParams qry1 (Only Chicken)
    Just (Only schwarma) <- firstRow result1
    liftBase $ print (schwarma :: Schwarma)
    result2 <- runQueryParams qry2 (Only (Person (Just "Faisal") (Just 24)))
    Just (Only person) <- firstRow result2
    liftBase $ print (person :: Person)
in
  void . withConnection "host=localhost port=5432 dbname=exampledb" $
    define setup
    & pqThen session
    & pqThen (define teardown)
:}
Chicken
Person {name = Just "Faisal", age = Just 24}
```
