### ISSUE TITLE
Deeply embed functions in schemas?

### ISSUE THREAD

**Issue by mikeplus64** [morphismtech/squeal#43]
Postgres supports user-defined functions, but squeal has no notion of it within schemas.

So concretely we should add, to `SchemumType`, a `Fundef` constructor.

We could go even further and embed *all* of the supported Postgres functions at the type-level within a "default" schema. This might be nice because some Postgres functions are only available if the user enables them; This would be pretty cool to have but also might necessitate, just for acceptable compile-times, having a type-level `Map` type...

**Comment by echatav** [comment]
See [https://www.postgresql.org/docs/10/static/extend.html](documentation) for user-defined extensions including functions, aggregates and operators.

**Comment by echatav** [comment]
I think it would be overly complex to treat _all_ functions as being user defined. Type level maps exist in the [type-level-sets](http://hackage.haskell.org/package/type-level-sets) package which I've played with adding as a dependency, though I decided against it for reasons I've now forgotten.

It's reasonable to target a useful subset of user extensions for functions, aggregates and operators (and maybe skip the operators, how would you name them?) rather than the full power of Postgres extensions if that overcomplicates. I had considered this before (see #4) but have not yet gotten around to it.

**Comment by mikeplus64** [comment]
It is proprietary sadly. It's for a web database thing to be used for a transport project.

I will probably release a `squeal-boilerplate` package soon-ish that is a mess of type families, TH, etc. for e.g. a `persistent`-esque `Entity` type, deriving `Schema`s from ordinary-looking Haskell types -- including deriving appropriate `createTable`s etc., and some other goodies. Most of it would be too opinionated, brittle, and spooky, to put into squeal proper, though :-).

It seems a bit like madness at the outset, but Squeal is a pretty good type-safe foundation to build complex combinators like these on top of. I'd use `hasql` if this weren't available.

**Comment by charlescrain** [comment]
Should this be closed? I can see `data SchemumType` has `Function [NullityType] ReturnsType` as a constructor. [link](https://github.com/morphismtech/squeal/blob/dev/squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs#L372)

If this has been done, are there any examples for defining user defined functions?

**Comment by echatav** [comment]
Hi Charles! I still need to write examples and documentation but yes he next version will have user defined functions and operators.

**Comment by charlescrain** [comment]
Hi Eitan! Awesomesauce!

**Comment by echatav** [comment]
Done in #209
