### ISSUE TITLE
Custom row definition / representing a sum type as a row

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#95]
I might be missing something, but I haven't found a way to encode a sum type as row to be able to pass it as a parameter and have automatic decoding from a row.

So basically I want to represent a type like 
```haskell
data Foo = A Int32 | B String
data Bar  = Bar { id :: Int32, body :: Foo }
```

with a table like:
```
id |   A   |  B
---+-------+---
1  |   1   | null
2  | null  | "Hello"
```

where the A/B columns have exactly one non-null value

I there a type class I can implement to explicitly convert the type from a Squeal `RowType`.

Do you have any suggestions on implementing such a table?

I am quite new to both Squeal and SQL. I am looking at representing it in this way in order to make it easy to index and search all `Foo` constructors.

**Comment by echatav** [comment]
This cannot be because of some arithmetic.

You want to try to represent the sum `a + b` as a product `(1+a)*(1+b)`, but these are not equal.

```
(1+a)*(1+b)=1+a+b+ab
```

There's an extra `1` and `ab` term. We can see this in the fact that the row `A null | B null` cannot be decoded into a `Foo` and the row `A 1 | B "Hello"` can't be decoded into a `Foo`.

**Comment by ilyakooo0** [comment]
Yes, the table can contain "invalid" rows. Just like a row can have a foreign key without an actual foreign value (if we don't add constraints), but we can add a constraint for that: https://dba.stackexchange.com/questions/5278/check-constraint-only-one-of-three-columns-is-non-null.

**Comment by ilyakooo0** [comment]
Yes, the table can contain "invalid" rows. Just like a row can have a foreign key without an actual foreign value (if we don't add constraints), but we can add a constraint for that: https://dba.stackexchange.com/questions/5278/check-constraint-only-one-of-three-columns-is-non-null.

**Comment by ilyakooo0** [comment]
I guess my question is whether I have a way of providing a

```haskell 
PG Bar -> '[ 'NotNull 'PGint4, 'Null PGint4, 'Null PGtext ]
```

representation without having to explicitly apply some sort of transformer

**Comment by echatav** [comment]
No, the `PG` type family transforms Haskell types into Postgres types. A different type family `RowPG` is used to transform Haskell record types into Postgres row types. But it is a closed type family so not user extensible. It takes a record and turns it into a row type in the obvious way:

```Haskell
>>> data Foo = Foo { bar :: Int32, baz :: Maybe Text } deriving (GHC.Generic, SOP.Generic, SOP.HasDatatypeInfo)
>>> :kind! RowPG Foo
RowPG Foo :: [(Symbol, NullityType)]
= '["bar" ::: 'NotNull 'PGint4, "baz" ::: 'Null 'PGtext]
```

There would be no obvious way to transform your `Foo` type into a Postgres row type as I pointed out because of the arithmetic of it.
